### ISSUE TITLE
Breaking changes after minor upgrade 1.14.5 -> 1.14.6

### ISSUE THREAD

**Issue by seagullua** [devtodev-analytics/android-sdk#5]
The method `CoreLog.setLogEnabled` became missing after upgrade 1.14.5 -> 1.14.6.

Stack:
`java.lang.NoSuchMethodError: No static method setLogEnabled(Z)V in class Lcom/devtodev/core/utils/log/CoreLog; or its super classes`

It was unexpected to get such a change in a minor upgrade. Now we have broken analytics in multiple games.

**Comment by RinatTalibullin** [comment]
Hello!

Do you have lines
```
-keep class com.devtodev.** { *; }
-dontwarn com.devtodev.**
```
included to your proguard configuration?

**Comment by RinatTalibullin** [comment]
Addressed issue was found and update will be available in few days.
